dsa/website/models.py
from flask import url_for
from dsa import db
from dsa.auth.models import Member


# a calendar event (meeting, etc.)
class Event(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(256),nullable=False)
    start = db.Column(db.DateTime, nullable=False,server_default=db.func.current_timestamp())
    

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    

class Election(db.Model):
    id = db.Column(db.Integer, primary_key=True)

dsa/__init__.py
import os

from dotenv import dotenv_values
import click
from pathlib import Path
from flask import Flask
from flask.cli import with_appcontext
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app(test_config=None):
    """
    Set up the application instance.
    """
    app = Flask(__name__,instance_relative_config=True)
    config = dotenv_values(".env")
    app.config.from_mapping(
        **config,
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
    )

    db.init_app(app)

    app.cli.add_command(init_db_command)
    app.cli.add_command(create_admin_command)

    from dsa import auth, website

    app.register_blueprint(auth.bp)
    app.register_blueprint(website.bp)

    app.add_url_rule("/", endpoint="index")

    return app


def init_db():
    """
    Database setup.
    """
    db.drop_all()
    db.create_all()


def create_admin(username, password, email):
    """
    Create a new user with admin privileges.
    """
    try:
        from .auth.models import Member, MemberRole
        new_member = Member(username=username, email=email, password=password)
        new_member.save()
        admin_role = MemberRole(role="administrator",member_id=new_member.id)
        db.session.add(admin_role)
        db.session.commit()
        return None

    except Exception as e:
        return str(e)


@click.command("create-admin")
@click.option("--username", default="admin", help="Username for admin account.")
@click.option("--password", default="admin", help="Password for admin account.")
@click.argument("email")
@with_appcontext
def create_admin_command(username, password, email):
    if (rslt := create_admin(username, password, email)) is not None:
        click.echo(f"Something went wrong: {rslt}.")

    else:
        click.echo("Admin account created.")


@click.command("init-db")
@with_appcontext
def init_db_command():
    init_db()
    click.echo("Database initialized.")

dsa/website/__init__.py
from .views import bp

dsa/website/views.py
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from dsa import db
from dsa.auth.models import Member
from dsa.auth.utils import login_required, role_required, csrf_view, render_form


bp = Blueprint("website", __name__)


@bp.route("/")
def index():
    """
    Show the homepage.
    """
    return render_template("website/index.html")


@bp.route("/about")
def about():
    """
    Show the about page.
    """
    return render_template("website/about.html")


@bp.route("/<int:member_id>", methods=("GET","POST"))
@login_required
@csrf_view
def home(member_id):
    """
    Shows the member panel.
    """
    member = Member.get_or_404(member_id)


@bp.route("/admin")
@role_required("administrator")
def admin():
    """
    Render the admin panel.
    """
    return render_template("admin/main.html")

dsa/templates/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} - Chapelboro DSA</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  </head>
  <body>
    <nav>
      <h1>Chapelboro DSA</h1>
      <ul>
	{% if g.user %}
	<li><span>{{ g.user['username']}}</span><li>
	<li><a href="{{ url_for('auth.logout') }}">log out</a></li>
	{% else %}
	<li><a href="{{ url_for('auth.register') }}">register</a></li>
	<li><a href="{{ url_for('auth.login') }}">log in</a></li>
	{% endif %}
	<li><a href="{{ url_for('website.index') }}">home</a></li>
	<li><a href="{{ url_for('website.about') }}"></a></li>
	<li><a href="https://www.dsausa.org">DSA National Homepage</a>
      </ul>
    </nav>
    <section class="content">
      <header>
	{% block header %}{% endblock %}
      </header>
      {% for message in get_flashed_messages() %}
      <div class="flash">{{ message }}</div>
      {% endfor %}
      {% block content %}{% endblock %}
    </section>
  </body>
</html>

dsa/templates/blog.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} - Chapelboro DSA</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  </head>
  <body>
    <nav>
      <h1>Chapelboro DSA</h1>
      <ul>
	{% if g.user %}
	<li><span>{{ g.user['username']}}</span><li>
	<li><a href="{{ url_for('auth.logout') }}">log out</a></li>
	{% else %}
	<li><a href="{{ url_for('auth.register') }}">register</a></li>
	<li><a href="{{ url_for('auth.login') }}">log in</a></li>
	{% endif %}
	<li><a href="{{ url_for('website.index') }}">home</a></li>
	<li><a href="{{ url_for('website.about') }}"></a></li>
	<li><a href="https://www.dsausa.org">DSA National Homepage</a>
      </ul>
    </nav>
    <section class="content">
      <header>
	{% block header %}{% endblock %}
      </header>
      {% for message in get_flashed_messages() %}
      <div class="flash">{{ message }}</div>
      {% endfor %}
      {% block content %}{% endblock %}
    </section>
  </body>
</html>

dsa/templates/form.html
{% extends 'base.html' %}

{# forms.html is helper macros, this is a default form template that includes the csrf token #}

{% from 'forms.html' import csrf with context %}

{% block header %}
<h1>{% block title %}{{ title }}{% endblock %}</h1>
{% endblock %}


{% block content %}
<form method="post">
  {{ csrf() }}
  {% block fields %}{% endblock %}
</form>
{% endblock %}

dsa/templates/forms.html
{% macro csrf() -%}
    <input type="text" name="csrf_token" value={{ csrf_token }} hidden>
{% endmacro %}

{% macro input(name, required=false, value='', placeholder='', type='text') -%}
    <input type="{{ type }}" value="{{ value|e }}" name="{{ name }}" id="{{ name }}" {% if required %}required{% endif %}>
{% endmacro %}

{% macro submit(msg) -%}
    <input type="submit" value="{{ msg|e }}">
{% endmacro %}    

{% macro textarea(name, value='', rows=10, cols=40) -%}
    <textarea name="{{ name }}" id="{{ name }}" rows="{{ rows }}" cols="{{ cols }}">
      {{ value|e }}
    </textarea>
{% endmacro %}

dsa/templates/website/about.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}About{% endblock %}</h1>
{% endblock %}

{% block content %}
<p> Just some about info, whatever</p>
{% endblock %}

dsa/templates/website/index.html
{% extends 'base.html' %}

{% block header %}
<h1>Welcome to Chapelboro DSA!</h1>
{% endblock %}


{% block content %}
<p>Join our fight today to make Chapel Hill a bolshevik worker's paradise!</p>
{% endblock %}